// <auto-generated />
using System;
using System.Text.Json;
using Beskar.Cluster.Database.Main.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beskar.Cluster.Database.Main.Migrations
{
    [DbContext(typeof(DbMainContext))]
    [Migration("20260427210120_SecondEditTest")]
    partial class SecondEditTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beskar.Cluster.Database.Main.Entities.System.DbSystemConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<JsonElement>("Value")
                        .HasColumnType("jsonb");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
